'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Check} from 'lucide-react';
import {properties} from '@/data/properties';

const steps=[
 {key:'purpose',q:'What are you buying for?',opts:['Own Stay','Investment','Holiday Home','Rental Income']},
 {key:'budget',q:'What is your budget?',opts:['Below RM600K','RM600K – RM800K','RM800K – RM1M','RM1M – RM1.5M','RM1.5M+']},
 {key:'location',q:'Preferred location?',opts:['Georgetown','Gelugor','Bayan Lepas','Tanjung Tokong','Batu Kawan','Not Sure']},
 {key:'priority',q:'What matters most?',opts:['Waterfront','Near LRT','Near Workplace','Family Friendly','Rental Potential','Low Entry Price']}
];
function inBudget(price:number,b:string){if(!b)return true;if(b==='Below RM600K')return price<600000;if(b.includes('600K – RM800K'))return price>=600000&&price<=800000;if(b.includes('800K – RM1M'))return price>800000&&price<=1000000;if(b.includes('RM1M – RM1.5M'))return price>1000000&&price<=1500000;return price>1500000}
export default function PropertyFinder({compact=false}:{compact?:boolean}){
 const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Record<string,string>>({});const [done,setDone]=useState(false);
 const matches=useMemo(()=>properties.filter(p=>inBudget(p.priceFrom,answers.budget||'')).map(p=>({p,score:(answers.purpose&&p.purposes.includes(answers.purpose)?2:0)+(answers.location&&answers.location!=='Not Sure'&&p.area===answers.location?3:0)+(answers.priority==='Waterfront'&&p.waterfront?2:0)+(answers.priority==='Near LRT'&&p.tags.includes('Near LRT')?2:0)+(answers.priority==='Family Friendly'&&p.tags.includes('Family Homes')?2:0)+(answers.priority==='Rental Potential'&&p.rentalPotential==='High'?2:0)+(answers.priority==='Low Entry Price'&&p.priceFrom<700000?2:0)})).sort((a,b)=>b.score-a.score).slice(0,3),[answers]);
 const choose=(v:string)=>{const a={...answers,[steps[step].key]:v};setAnswers(a);if(step<steps.length-1)setStep(step+1);else setDone(true)};
 return <div className={`overflow-hidden rounded-[30px] ${compact?'bg-white':'bg-white shadow-soft'}`}>{!done?<div className="p-6 md:p-9"><div className="flex items-center justify-between"><span className="eyebrow text-ink/40">Property Finder</span><span className="text-xs font-bold text-ink/35">{step+1} / 4</span></div><div className="mt-3 h-1 overflow-hidden rounded-full bg-black/5"><div className="h-full bg-ink transition-all" style={{width:`${(step+1)*25}%`}}/></div><h3 className="display mt-7 text-3xl font-semibold md:text-4xl">{steps[step].q}</h3><div className="mt-6 grid gap-2 sm:grid-cols-2">{steps[step].opts.map(o=><button onClick={()=>choose(o)} key={o} className="group flex items-center justify-between rounded-2xl border border-black/10 p-4 text-left text-sm font-bold transition hover:border-ink hover:bg-ink hover:text-white"><span>{o}</span><ArrowRight size={17} className="opacity-35 group-hover:opacity-100"/></button>)}</div>{step>0&&<button onClick={()=>setStep(step-1)} className="mt-5 text-sm text-ink/50 underline">Back</button>}</div>:<div className="p-6 md:p-9"><div className="eyebrow text-ink/40">Your matches</div><h3 className="display mt-3 text-3xl font-semibold md:text-4xl">A shorter list to start with.</h3><div className="mt-6 grid gap-3">{matches.map(({p})=><Link href={`/properties/${p.slug}`} key={p.slug} className="flex items-center justify-between rounded-2xl bg-paper p-4"><div><div className="text-xs text-ink/45">{p.location}</div><div className="mt-1 font-bold">{p.name}</div><div className="mt-1 text-sm text-ink/55">{p.priceLabel} · {p.builtUp}</div></div><div className="flex h-9 w-9 items-center justify-center rounded-full bg-ink text-white"><ArrowRight size={16}/></div></Link>)}</div><div className="mt-5 rounded-2xl bg-ink p-5 text-white"><div className="flex gap-2 text-sm font-bold"><Check size={17}/>Want me to narrow it down further?</div><p className="mt-2 text-sm leading-6 text-white/55">Send your preferences to ZiHan and ask for the latest price, unit availability and floor plans.</p><a href={`https://wa.me/60126564155?text=${encodeURIComponent(`Hi ZiHan, I used your Property Finder. I'm buying for ${answers.purpose}, budget ${answers.budget}, preferred area ${answers.location}, and I care most about ${answers.priority}. Can you help me shortlist?`)}`} className="mt-4 inline-flex rounded-full bg-acid px-5 py-3 text-sm font-bold text-ink">WhatsApp My Preferences</a></div><button onClick={()=>{setDone(false);setStep(0);setAnswers({})}} className="mt-5 text-sm text-ink/50 underline">Start again</button></div>}</div>
}
