import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,MapPin,SlidersHorizontal,MessageCircle,CheckCircle2} from 'lucide-react';
import PropertyFinder from '@/components/PropertyFinder';
import PropertyCard from '@/components/PropertyCard';
import SectionHeading from '@/components/SectionHeading';
import AffordabilityCalculator from '@/components/AffordabilityCalculator';
import {properties,lifestyles} from '@/data/properties';
import {insights} from '@/data/insights';

export default function Home(){return <main>
<section className="relative min-h-[92vh] overflow-hidden bg-ink text-white"><Image src="https://images.pexels.com/photos/31019096/pexels-photo-31019096.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Penang skyline and waterfront" fill priority className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,13,11,.92)_0%,rgba(8,13,11,.64)_46%,rgba(8,13,11,.18)_100%)]"/><div className="container-x relative flex min-h-[92vh] items-end pb-16 pt-32 md:items-center md:pb-0"><div className="max-w-3xl"><div className="eyebrow mb-5 text-white/45">Penang Property · Curated by ZiHan</div><h1 className="display text-6xl font-semibold leading-[.92] md:text-[92px]">Find the Right<br/>Penang Property.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/68">Tell us your budget, lifestyle and purpose. We’ll help narrow down the right options for you.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#finder" className="flex items-center gap-2 rounded-full bg-acid px-6 py-3.5 font-bold text-ink">Find My Property <ArrowRight size={18}/></Link><Link href="/properties" className="rounded-full border border-white/25 bg-white/5 px-6 py-3.5 font-bold">Browse Properties</Link></div><div className="mt-12 grid max-w-2xl grid-cols-3 gap-4 border-t border-white/15 pt-5 text-sm text-white/55"><span>By budget</span><span>By lifestyle</span><span>By purpose</span></div></div></div></section>

<section id="finder" className="bg-ink pb-24 text-white"><div className="container-x grid items-start gap-10 md:grid-cols-[.8fr_1.2fr]"><div className="pt-4 md:sticky md:top-28"><div className="eyebrow text-white/40">A smarter starting point</div><h2 className="display mt-3 text-4xl font-semibold leading-tight md:text-6xl">Four questions.<br/>A much shorter list.</h2><p className="mt-5 max-w-md text-base leading-7 text-white/55">Instead of scrolling through dozens of projects, start with what actually matters to your decision.</p><div className="mt-8 grid gap-3 text-sm text-white/65">{['Budget first, not brochure first','Match location to your real routine','Separate own-stay needs from investment goals'].map(x=><div className="flex items-center gap-3" key={x}><CheckCircle2 size={18}/>{x}</div>)}</div></div><PropertyFinder/></div></section>

<section className="section-pad"><div className="container-x"><div className="flex items-end justify-between gap-4"><SectionHeading eyebrow="Featured properties" title="A curated shortlist, not an endless catalogue." body="A mix of island, waterfront, family and investment-oriented options to help you compare different Penang property profiles."/><Link href="/properties" className="mb-10 hidden items-center gap-2 text-sm font-bold md:flex">View all <ArrowRight size={17}/></Link></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{properties.slice(0,6).map(p=><PropertyCard p={p} key={p.slug}/>)}</div></div></section>

<section className="section-pad bg-[#E7EAE4]"><div className="container-x"><SectionHeading eyebrow="Discover by lifestyle" title="Start with the life you want around the property." body="Some buyers care about the view. Some care about a 10-minute commute. Use lifestyle filters to get closer to the right answer."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{lifestyles.map((x,i)=><Link href={`/properties?tag=${encodeURIComponent(x)}`} key={x} className={`group min-h-48 rounded-[24px] p-5 transition hover:-translate-y-1 ${i%3===0?'bg-ink text-white':'bg-white'}`}><div className="flex items-start justify-between"><span className={`text-xs font-bold ${i%3===0?'text-white/35':'text-ink/35'}`}>0{i+1}</span><ArrowRight size={17}/></div><div className="mt-20 text-2xl font-bold">{x}</div></Link>)}</div></div></section>

<section className="section-pad bg-ink text-white"><div className="container-x"><SectionHeading eyebrow="Compare smarter" title="Put the important numbers side by side." body="Price, tenure, size, access, waterfront, rental potential and estimated instalment — without jumping between tabs." invert/><div className="grid gap-3 md:grid-cols-3">{properties.slice(0,3).map(p=><div key={p.slug} className="rounded-[24px] border border-white/10 bg-white/5 p-5"><div className="text-sm text-white/45">{p.location}</div><div className="mt-1 text-2xl font-bold">{p.name}</div><div className="mt-8 grid grid-cols-2 gap-y-4 text-sm"><span className="text-white/35">Price</span><span>{p.priceLabel}</span><span className="text-white/35">Tenure</span><span>{p.tenure}</span><span className="text-white/35">Built-up</span><span>{p.builtUp}</span><span className="text-white/35">LRT</span><span>{p.lrt}</span></div></div>)}</div><div className="mt-7 flex flex-wrap items-center justify-between gap-4 rounded-[24px] bg-white p-5 text-ink"><div><div className="text-lg font-bold">Not sure which one fits you?</div><div className="text-sm text-ink/50">Compare up to 3 properties, then ask ZiHan.</div></div><div className="flex gap-2"><Link href="/compare" className="rounded-full border border-ink/15 px-5 py-3 text-sm font-bold">Compare Projects</Link><a href="https://wa.me/60126564155" className="rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">WhatsApp ZiHan</a></div></div></div></section>

<section className="section-pad"><div className="container-x"><SectionHeading eyebrow="Affordability calculator" title="What price range feels comfortable — not just possible?" body="Use a quick estimate before you start shortlisting. It is a guide, not a bank approval."/><AffordabilityCalculator/></div></section>

<section className="section-pad bg-white"><div className="container-x"><SectionHeading eyebrow="ZiHan Explains" title="Property makes more sense when the numbers do." body="Plain-language guides on Penang property, loans, policy, tax, EPF and the market around your buying decision."/><div className="grid gap-4 md:grid-cols-2">{insights.map((a,i)=><Link href={`/insights/${a.slug}`} key={a.slug} className="group rounded-[24px] border border-black/10 p-6 transition hover:bg-ink hover:text-white"><div className="flex items-center justify-between"><span className="eyebrow opacity-40">{a.category}</span><span className="text-xs opacity-40">{a.read}</span></div><h3 className="display mt-8 text-3xl font-semibold leading-tight">{a.title}</h3><p className="mt-4 text-sm leading-6 opacity-55">{a.excerpt}</p><ArrowRight className="mt-8"/></Link>)}</div></div></section>

<section className="relative overflow-hidden bg-[#DCE5DB]"><div className="container-x grid items-center gap-8 py-20 md:grid-cols-[1fr_.75fr]"><div><div className="eyebrow text-ink/40">About ZiHan</div><h2 className="display mt-3 max-w-2xl text-5xl font-semibold leading-[1] md:text-7xl">Help first.<br/>Narrow the options.<br/>Then decide.</h2><p className="mt-5 max-w-xl leading-7 text-ink/60">Hi, I’m ZiHan. I started my property sales career in 2013. I prefer helping buyers understand the numbers, location, lifestyle and long-term considerations behind a property decision — instead of simply pushing a project.</p><a href="https://wa.me/60126564155" className="mt-7 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 font-bold text-white"><MessageCircle size={18}/> Talk to ZiHan</a></div><div className="rounded-[28px] bg-ink p-7 text-white"><div className="eyebrow text-white/35">A useful first message</div><p className="display mt-4 text-3xl leading-tight">“My budget is RM700K–RM800K. I’m buying for own stay, and I want somewhere convenient to Bayan Lepas. What should I compare?”</p><div className="mt-8 flex items-center gap-3 text-sm text-white/50"><SlidersHorizontal size={17}/> Better inputs → better shortlist</div></div></div></section>
</main>}
